### ISSUE TITLE
Problems with complex input matrices?

### ISSUE THREAD

**Issue by Codedial06** [melihaltun/complexEigenPairSolver#1]
Hi, in the description it says that this also works for complex input matrices, but i only get NAN outputs, please help, thank you!!

**Comment by melihaltun** [comment]
I see the issue. It is possibly because solve2by2eig() function in eigenPairs.cpp assumes the input is real and performs the eigen decomposition using only the real parts of the input matrix. 
I need to figure out how the discriminant approach in the function can be modified to work with complex inputs.

**Comment by melihaltun** [comment]
Fixed with the commit:
https://github.com/melihaltun/complexEigenPairSolver/commit/b3ff2947cddf8cc2d0c0b83d5e3d90fd7e05f110
